name: oly
channels:
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - beautifulsoup4=4.12.3
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.8
  - freetype=2.12.1
  - fuzzywuzzy=0.18.0
  - geographiclib=2.0
  - geopy=2.4.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - levenshtein=0.26.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libopenblas=0.3.28
  - libpng=1.6.46
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxgboost=2.1.3
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.2.2
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.3
  - pyaml=25.1.0
  - pycountry=24.6.1
  - pygments=2.19.1
  - pyparsing=3.2.1
  - python=3.13.1
  - python-dateutil=2.9.0.post0
  - python-levenshtein=0.26.1
  - python-tzdata=2025.1
  - python_abi=3.13
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - rapidfuzz=3.12.1
  - readline=8.2
  - scikit-learn=1.5.2
  - scikit-optimize=0.10.2
  - scipy=1.15.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - soupsieve=2.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wcwidth=0.2.13
  - xgboost=2.1.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstd=1.5.6
  